apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-svc-3
  namespace: messaging
  labels:
    service: kafka-broker-svc-3
spec:
  ports:
  - name: kafka-broker-svc-3-port
    targetPort: 9092
    port: 9092
    nodePort: 32403
    protocol: TCP
  - name: kafka-broker-3-jmx-port
    targetPort: 7203
    port: 7203
    protocol: TCP
  selector:
    app: kafka-broker-3
  type: NodePort
