apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-svc-4
  namespace: messaging
  labels:
    service: kafka-broker-svc-4
spec:
  ports:
  - name: kafka-broker-svc-4-port
    targetPort: 9092
    port: 9092
    nodePort: 32404
    protocol: TCP
  - name: kafka-broker-4-jmx-port
    targetPort: 7203
    port: 7203
    protocol: TCP
  selector:
    app: kafka-broker-4
  type: NodePort
