apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment-2
  namespace: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper-2
        image: foundery.azurecr.io/foundery/zookeeper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2183
        - containerPort: 2888
        - containerPort: 3888
        env:
        - name: ZOOKEEPER_ID
          value: "2"
      imagePullSecrets:
      - name: dockerprivateregistrykey
