apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc-3
  namespace: messaging
  labels:
    service: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - name: zookeeper-3-client-port
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: zookeeper-3-port-leader
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: zookeeper-3-leader-election-port
      protocol: TCP
      port: 3888
      targetPort: 3888
  type: NodePort
