apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-svc-1
  namespace: messaging
  labels:
    service: kafka-broker-svc-1
spec:
  ports:
  - name: kafka-broker-svc-1-port
    targetPort: 9092
    port: 9092
    nodePort: 32401
    protocol: TCP
  - name: kafka-broker-1-jmx-port
    targetPort: 7203
    port: 7203
    protocol: TCP
  selector:
    app: kafka-broker-1
  type: NodePort
