apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-svc-2
  namespace: messaging
  labels:
    service: kafka-broker-svc-2
spec:
  ports:
  - name: kafka-broker-svc-2-port
    targetPort: 9092
    port: 9092
    nodePort: 32402
    protocol: TCP
  - name: kafka-broker-2-jmx-port
    targetPort: 7203
    port: 7203
    protocol: TCP
  selector:
    app: kafka-broker-2
  type: NodePort
